version: '3.4'

services:
  howtoaks-web:
    image: howtoaks-web
    container_name: howtoaks-web
    build:
      context: ./HowToAKS.Web
    ports:
      - 8080:80

  howtoaks-webapi:
    image: howtoaks-webapi
    container_name: howtoaks-webapi
    build:
      context: ./HowToAKS.WebApi
    ports:
      - 8081:80