# with default namespace

apiVersion: apps/v1
kind: Deployment
metadata:
  name: howtoaks-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: howtoaks-web
  template:
    metadata:
      labels:
        app: howtoaks-web
    spec:
      containers:
      - name: howtoaks-web
        image: your-acr-address.azurecr.io/howtoaks-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---    

apiVersion: v1
kind: Service
metadata:
  name: howtoaks-web
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: howtoaks-web
    
---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: howtoaks-webapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: howtoaks-webapi
  template:
    metadata:
      labels:
        app: howtoaks-webapi
    spec:
      containers:
      - name: howtoaks-webapi
        image: your-acr-address.azurecr.io/howtoaks-webapi:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: howtoaks-webapi
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 80
  selector:
    app: howtoaks-webapi


# with custom defined namespaces (front-end & back-end)

# apiVersion: v1
# kind: Namespace
# metadata:
#   name: front-end
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: back-end
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: howtoaks-web
#   namespace: front-end
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: howtoaks-web
#   template:
#     metadata:
#       labels:
#         app: howtoaks-web
#     spec:
#       containers:
#       - name: howtoaks-web
#         image: devneacrhowtoaks.azurecr.io/howtoaks-web:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 80
# ---  
# apiVersion: v1
# kind: Service
# metadata:
#   name: howtoaks-web
#   namespace: front-end
# spec:
#   type: LoadBalancer
#   ports:
#   - protocol: TCP
#     port: 8080
#     targetPort: 80
#   selector:
#     app: howtoaks-web
# ---  
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: howtoaks-webapi
#   namespace: back-end
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: howtoaks-webapi
#   template:
#     metadata:
#       labels:
#         app: howtoaks-webapi
#     spec:
#       containers:
#       - name: howtoaks-webapi
#         image: devneacrhowtoaks.azurecr.io/howtoaks-webapi:latest
#         ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: howtoaks-webapi
#   namespace: back-end 
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 8081
#     targetPort: 80
#   selector:
#     app: howtoaks-webapi
  


  

